language: cpp
os:
 - linux
sudo: true
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

env:
 - CPP=g++-4.9 GCC=gcc-4.9 BUILD_TYPE=Release CONAN="-s compiler.version=4.9 -s build_type=Release" COVERAGE=NO
 - CPP=g++-4.9 GCC=gcc-4.9 BUILD_TYPE=Debug   CONAN="-s compiler.version=4.9 -s build_type=Debug"   COVERAGE=YES

install:
 - wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-ubuntu-64_0_9_2.deb -O conan.deb || exit 1
 - sudo dpkg -i conan.deb || exit 1
 - rm conan.deb || exit 1
 - conan --version

 - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
 - tar -xzf cmake-3.0.2-Linux-64.tar.gz
 - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
 - rm -rf cmake-3.0.2-Linux-64
 - rm cmake-3.0.2-Linux-64.tar.gz

script:
 - mkdir build
 - pushd build
 - CXX=$CPP CC=$GCC conan install --build silicium --build ventura --build Beast -s compiler=gcc $CONAN .. || exit 1
 - CXX=$CPP CC=$GCC cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARPCOIL_WARNING_IS_ERROR=ON -DWARPCOIL_USE_CLANG_FORMAT=OFF -DWARPCOIL_COVERAGE=$COVERAGE || exit 1
 - cmake --build . -- -j2 || exit 1
 - pushd bin
 - ./tests || exit 1
 - if [ $COVERAGE == "YES" ]; then
     curl -s https://codecov.io/bash > codecov.sh || exit 1;
     chmod +x codecov.sh || exit 1;
     ./codecov.sh -v -x gcov-4.9 || exit 1;
   fi
